package com.example.cit_app.data_access;

import com.example.cit_app.data_access.FeatureDADao;
import com.example.cit_app.data_access.PatientDADao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig featureDADaoConfig;
    private final DaoConfig patientDADaoConfig;

    private final FeatureDADao featureDADao;
    private final PatientDADao patientDADao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        featureDADaoConfig = daoConfigMap.get(FeatureDADao.class).clone();
        featureDADaoConfig.initIdentityScope(type);

        patientDADaoConfig = daoConfigMap.get(PatientDADao.class).clone();
        patientDADaoConfig.initIdentityScope(type);

        featureDADao = new FeatureDADao(featureDADaoConfig, this);
        patientDADao = new PatientDADao(patientDADaoConfig, this);

        registerDao(FeatureDA.class, featureDADao);
        registerDao(PatientDA.class, patientDADao);
    }
    
    public void clear() {
        featureDADaoConfig.clearIdentityScope();
        patientDADaoConfig.clearIdentityScope();
    }

    public FeatureDADao getFeatureDADao() {
        return featureDADao;
    }

    public PatientDADao getPatientDADao() {
        return patientDADao;
    }

}
